const $=id=>document.getElementById(id);
const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const canonical=s=>({'Rose AI':'Rose','Old Snake':'Solid Snake','Naked Snake':'Big Boss','Revolver Ocelot':'Ocelot','Meryl Silverburgh':'Meryl','Colonel Volgin':'Volgin'}[s]||s);
const label=s=>s==='Solid Snake'?'Solid Snake / Old Snake':s==='Big Boss'?'Big Boss / Naked Snake':s==='Ocelot'?'Ocelot / Revolver Ocelot':s;
const rosters={DS1:['Sam Porter Bridges','Fragile','Cliff Unger','Deadman','Heartman','Higgs','Amelie','Die-Hardman','Mama','Lockne','Bridget Strand'],DS2:['Sam Porter Bridges','Fragile','Higgs','Dollman','Rainy','Tomorrow','Tarman','Deadman','Heartman','Neil Vana','Die-Hardman'],MGS1:['Solid Snake','Ocelot','Liquid Snake','Meryl','Otacon','Naomi Hunter','Gray Fox','Sniper Wolf','Psycho Mantis','Vulcan Raven'],MGS2:['Solid Snake','Raiden','Solidus Snake','Colonel AI','Rose','Fortune','Fatman','Vamp','Otacon','Ocelot'],MGS3:['Big Boss','The Boss','EVA','Ocelot','Volgin','The Sorrow','The End','The Fury','Major Zero'],MGS4:['Solid Snake','Raiden','Big Boss','Liquid Ocelot','Naomi Hunter','Otacon','Meryl','Drebin'],PW:['Big Boss','Paz','Kazuhira Miller','Chico','Huey','Strangelove','Hot Coldman'],GZ:['Big Boss','Paz','Chico','Kazuhira Miller','Skull Face'],TPP:['Venom Snake','Kazuhira Miller','Ocelot','Skull Face','Huey','Quiet','Code Talker'],RISING:['Raiden','Jetstream Sam','Monsoon','Mistral','Sundowner','Senator Armstrong','Boris','Doktor','Blade Wolf']};
const CHARACTER_ONLY=typeof QUIZ_MODE!=='undefined'&&QUIZ_MODE==='character';
const MAX_POINTS=CHARACTER_ONLY?10:20;
const MGS_RANKS=[{name:'Foxhound',min:20},{name:'Fox',min:18},{name:'Doberman',min:16},{name:'Hound',min:14},{name:'Eagle',min:12},{name:'Hawk',min:10},{name:'Wolf',min:6},{name:'Chicken',min:0}];
function missionRank(points){return MGS_RANKS.findIndex(rank=>points>=rank.min)}
function rankEmblem(name){const icon=document.createElement('span');icon.className='rank-emblem';const img=document.createElement('img');img.src='rank-'+name.toLowerCase()+'.png';img.alt=name+' emblem from Metal Gear Solid V';icon.append(img);return icon}
function rankResults(){
  const placement=missionRank(score),rank=MGS_RANKS[placement],panel=document.createElement('section');panel.className='rank-report';
  const caption=document.createElement('p');caption.className='rank-caption';caption.textContent='CODENAME AWARDED';
  const title=document.createElement('h3');title.className='rank-name';title.textContent=rank.name.toUpperCase();const award=document.createElement('div');award.className='rank-award';award.append(rankEmblem(rank.name),title);
  const standing=document.createElement('p');standing.className='rank-standing';standing.textContent=Math.round(score/20*100)+'% ACCURACY · RANK '+(placement+1)+' OF '+MGS_RANKS.length;
  const progress=document.createElement('p');progress.className='rank-progress';const gap=placement?MGS_RANKS[placement-1].min-score:0;progress.textContent=placement?gap+' more correct '+(gap===1?'answer':'answers')+' for '+MGS_RANKS[placement-1].name+'.':'Perfect mission. Highest rank achieved.';
  const ladder=document.createElement('ol');ladder.className='rank-ladder';
  MGS_RANKS.forEach((tier,i)=>{const row=document.createElement('li');row.className='rank-row'+(i===placement?' current':'');const name=document.createElement('span');name.textContent=String(i+1).padStart(2,'0')+' / '+tier.name.toUpperCase();const range=document.createElement('span');const max=i?MGS_RANKS[i-1].min-1:20;range.textContent=(tier.min===max?tier.min*5:tier.min*5+'–'+max*5)+'%';const marker=document.createElement('strong');marker.textContent=i===placement?'YOU':'';row.append(rankEmblem(tier.name),name,range,marker);ladder.append(row)});
  const note=document.createElement('p');note.className='rank-note';note.textContent='MGS codenames · Quiz score thresholds';const credits=document.createElement('a');credits.href='rank-sources.json';credits.className='rank-note rank-art-source';credits.textContent='Original emblem artwork: MGSV';panel.append(caption,award,standing,progress,ladder,note,credits);return panel;
}
function characterOptions(q){const correct=canonical(q.speaker);const cast=CHARACTER_ONLY?[...rosters.DS1,...rosters.DS2]:rosters[q.game]||[];const pool=CHARACTER_ONLY?QUOTES:QUOTES.filter(x=>x.game===q.game);const candidates=[...new Set([...cast,...pool.map(x=>canonical(x.speaker))])].filter(s=>s!==correct);return shuffle([correct,...shuffle(candidates).slice(0,3)])}
let deck=[],position=0,score=0,gameScore=0,characterScore=0,answeredCount=0,stage='game',options=[],gameResult=null,characterResult=null;
function start(){deck=shuffle(QUOTES).slice(0,10);position=score=gameScore=characterScore=answeredCount=0;$('summary').hidden=true;render()}
function updateScore(){$('score').textContent=String(score).padStart(2,'0');$('accuracy').textContent=answeredCount?Math.round(score/answeredCount*100)+'%':'—';$('meter').style.width=answeredCount/MAX_POINTS*100+'%'}
function choices(){const action=stage==='game'?guess:guessCharacter;$('choices').hidden=false;$('choices').replaceChildren(...options.map((value,i)=>{const b=document.createElement('button');b.className='choice';const n=document.createElement('span');n.className='number';n.textContent=i+1;const t=document.createElement('span');t.className='game-name';t.textContent=stage==='game'?GAMES[value].title:label(value);b.append(n,t);b.onclick=()=>action(value);return b}))}
function render(){stage='game';gameResult=characterResult=null;const q=deck[position];if(typeof updateHologram==='function')updateHologram(q,false);$('quote').textContent=q.text;$('quote').className=q.text.length>160?'long-quote':'';$('speaker').textContent='SPEAKER CLASSIFIED';$('round').textContent=String(position+1).padStart(2,'0');updateScore();$('reveal').hidden=true;$('choice-title').textContent='1 / 2 — Identify the game';$('key-note').textContent='SELECT 1–4';options=shuffle([q.game,...shuffle(Object.keys(GAMES).filter(g=>g!==q.game)).slice(0,3)]);if(CHARACTER_ONLY){stage='character';options=characterOptions(q);$('choice-title').textContent='Who said it?'}$('key-note').textContent='SELECT 1–'+options.length;choices();$('pool').textContent=QUOTES.length+' QUOTES IN ARCHIVE';$('archive-count').textContent=QUOTES.length+' QUOTES / '+Object.keys(GAMES).length+' GAMES'}
function guess(game){if(stage!=='game'||!options.includes(game))return {error:'Choose an available game for this stage.'};const q=deck[position];gameResult=game===q.game;if(gameResult){score++;gameScore++}answeredCount++;stage='character';updateScore();const correct=canonical(q.speaker);const candidates=[...new Set([...(rosters[q.game]||[]),...QUOTES.filter(x=>x.game===q.game).map(x=>canonical(x.speaker))])].filter(s=>s!==correct);options=shuffle([correct,...shuffle(candidates).slice(0,3)]);$('choice-title').textContent='2 / 2 — Who said it?';$('key-note').textContent='SELECT 1–4';choices();showReveal(false);$('choices').children[0].focus({preventScroll:true});return {correct:gameResult,game:GAMES[q.game].title,nextStage:'character',score}}
function guessCharacter(character){if(stage!=='character'||!options.includes(character))return {error:'Choose one of the available characters.'};const q=deck[position],correct=canonical(q.speaker);characterResult=character===correct;if(characterResult){score++;characterScore++}answeredCount++;stage='revealed';updateScore();Array.from($('choices').children).forEach((b,i)=>{b.disabled=true;b.classList.add(options[i]===correct?'correct':options[i]===character?'wrong':'dimmed')});$('speaker').textContent=q.speaker.toUpperCase();if(typeof updateHologram==='function')updateHologram(q,true);$('key-note').textContent='TRANSMISSION DECODED';showReveal(true);return {correct:characterResult,speaker:q.speaker,score}}
function showReveal(complete){const q=deck[position],g=GAMES[q.game],r=$('reveal');r.className="reveal"+(!CHARACTER_ONLY&&gameResult===false?" game-incorrect":"");r.replaceChildren();const img=document.createElement('img');img.src=g.cover;img.alt=g.title+' game cover';img.onerror=()=>{img.alt='Cover unavailable: '+g.title};const detail=document.createElement('div');const result=document.createElement('div');const correct=CHARACTER_ONLY?characterResult:gameResult;result.className='result'+(correct?'':' missed');result.textContent=CHARACTER_ONLY?(correct?'CORRECT · +1 POINT':'INCORRECT · SPEAKER REVEALED'):(gameResult?'GAME CORRECT · +1 POINT':'GAME INCORRECT');const title=document.createElement('h3');title.textContent=g.title;const speaker=document.createElement('p');speaker.textContent=complete?q.speaker+' · '+(characterResult?'CHARACTER CORRECT · +1 POINT':'CHARACTER INCORRECT'):'Speaker classified — choose the character above.';detail.append(result,title,speaker);r.append(img,detail);if(complete){if(q.source){const a=document.createElement('a');a.className='source';a.href=q.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Quote source';detail.append(a)}const next=document.createElement('button');next.className='next';next.textContent=position===9?'Mission results':'Next transmission';next.onclick=advance;r.append(next);next.focus({preventScroll:true})}r.hidden=false}
function advance(){if(stage!=='revealed')return {error:'Answer the current question first.'};if(position<9){position++;render()}else{stage='complete';$('choices').hidden=true;$('reveal').hidden=true;$('choice-title').textContent='Mission complete';$('key-note').textContent='END OF TRANSMISSION';const s=$('summary');s.replaceChildren();const h=document.createElement('h2');h.textContent=score+' / '+MAX_POINTS+' points';const p=document.createElement('p');p.textContent=CHARACTER_ONLY?'Characters: '+characterScore+' / 10':'Games: '+gameScore+' / 10 · Characters: '+characterScore+' / 10';const b=document.createElement('button');b.className='next';b.textContent='Play another round';b.onclick=start;s.append(h,p);if(!CHARACTER_ONLY)s.append(rankResults());s.append(b);s.hidden=false;b.focus({preventScroll:true})}return {round:position+1,score,stage}}
document.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const n=Number(e.key);if((stage==='game'||stage==='character')&&n>=1&&n<=options.length){e.preventDefault();stage==='game'?guess(options[n-1]):guessCharacter(options[n-1])}});
start();
if(document.modelContext?.registerTool){const schema=key=>({type:'object',properties:{[key]:{type:'string'}},required:[key],additionalProperties:false});const validate=(input,key)=>{if(!input||typeof input[key]!=='string'||Object.keys(input).length!==1)throw Error('Supply one '+key+' value.');return input[key]};const tools=[{name:'read_quiz',description:'Read the current quote, stage and available choices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({quote:deck[position].text,options:options.map(id=>({id,title:stage==='game'?GAMES[id].title:label(id)})),stage,round:position+1,score})},{name:'guess_game',description:'Guess the game, show its cover and open the character question.',inputSchema:schema('game'),execute:input=>guess(validate(input,'game'))},{name:'guess_character',description:'Guess the character and reveal the speaker.',inputSchema:schema('character'),execute:input=>guessCharacter(validate(input,'character'))},{name:'next_transmission',description:'Advance after the current quote is answered.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>advance()}];for(const tool of tools.filter(t=>!CHARACTER_ONLY||t.name!=='guess_game')){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
